import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1>About</h1>
        <p>
          This is About page. You can edit me at <code>/pages/about.js</code>
        </p>
        <Link href="/">
          <a className="button" style={{ marginTop: '1rem' }}>
            Back to Home
          </a>
        </Link>
      </div>
    </>
  );
}
